spring:
  datasource:
    url: jdbc:posgresql://${datasource.host}:${datasource.port}/${datasource.database}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: org.postgresql.Driver

datasource:
  host: ${DATASOURCE_HOST:localhost}
  port: ${DATASOURCE_PORT:5434}
  username: ${DATABASE_USERNAME:tap}
  password: ${DATABASE_PASSWORD:tap}
  database: ${DATASOURCE_DATABASE:tap}

xmpp:
  domain: ${XMPP_DOMAIN:jabber.hot-chilli.net}
  userName: ${XMPP_USERNAME:timestamp-ap}
  password: ${XMPP_PASSWORD:timestamp-ap}
  host: ${XMPP_HOST:jabber.hot-chilli.net}

server:
  port: 8081

web3:
  host: ${WEB3_HOST:http://localhost:8545}