spring:
  datasource:
    url: jdbc:posgresql://${datasource.host}:${datasource.port}/${datasource.database}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: org.postgresql.Driver

datasource:
  host: ${DATASOURCE_HOST:localhost}
  port: ${DATASOURCE_PORT:5434}
  username: ${DATABASE_USERNAME:tap}
  password: ${DATABASE_PASSWORD:tap}
  database: ${DATASOURCE_DATABASE:tap}

xmpp:
  domain: ${XMPP_DOMAIN:xmpp.kyc3.com}
  password: ${XMPP_PASSWORD:tap}
  host: ${XMPP_HOST:xmpp.kyc3.com}

attestation:
  redirect:
    base_url: ${ATTESTATION_REDIRECT_URL:http://localhost:4201}/attestation
oracle:
  address: ${ORACLE_ADDRESS:0xf2064cbc3c9f859780AE939739f8054E289d9542}
  redirect:
    base_url: ${ORACLE_REDIRECT_URL:http://localhost:4200}/nft/purchase-complete

wallet:
  privateKey: ${ACCOUNT_PRIVATE_KEY:e5cdf22794357fa5e03e4c92bb1a71c52817669fb6eb60663d8d341e0fdb8a03}

logging:
  level:
    root: INFO

server:
  port: 8081

web3:
  host: ${WEB3_HOST:https://public-node.testnet.rsk.co}

libsodium:
  path: ${LIBSODIUM_PATH:/usr/lib/libsodium.so}

contracts:
  cashier: ${CASHIER_CONTRACT_ADDRESS:0x7b7Ec4C333fC5E3D0B4001fC818491A7AE59a407}
  trust-token: ${TRUST_TOKEN_ADDRESS:0x053965Ca43f024d701AA4bF5c39db8aAcfCCF1A0}
  erc20: ${ERC20_ADDRESS:0x4d26774771a9D7CA38Ae419b695deC042B25e98d}